### ISSUE TITLE
plugin request for opencart 1.5.6.x

### ISSUE THREAD

**Issue by mikebanson** [ciriusrob/hubtel-opencart#1]
hi, this plugin is wonderful and thank you. i would like to request for lower opencart 1.5.x. will be glad if it can be don

**Comment by ciriusrob** [comment]
Hi mike. Am glad you liked it. I however don't have any plans for 1.5.x yet. At least not in the near future. Also, please use the email provided in the readme for such request henceforth. Thank you.

**Comment by mikebanson** [comment]
ok. thank you
